tsc: allow decorators
jodit library uses decorators, leading to error TS1219
 (currently ignored with @ts-ignore, which is rejected by ESlint)
  → allow decorators (already allowed in jodit' tsconfig.json)